apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
      annotations:
        checksum/config: "init"
    spec:
      containers:
      - name: sampleapi
        image: sampleapi-image
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: sampleapi-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
