apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - .env
  literals:
  - AzureAd__Roles__0=Forecast.Read
  name: sampleapi-config
images:
- name: sampleapi-image
  newName: acrwisampleenv.azurecr.io/wi-sample/sampleapi-env
  newTag: azd-deploy-1755677205
