apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- service-account.yaml
- deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - .env
  literals:
  - AZURE_AUTHORITY_HOST=https://login.microsoftonline.com
  name: samplefe-config
replacements:
- source:
    fieldPath: data.AzureAd__ClientId
    kind: ConfigMap
    name: samplefe-config
  targets:
  - fieldPaths:
    - metadata.annotations.[azure.workload.identity/client-id]
    select:
      kind: ServiceAccount
      name: workload-identity-sa
images:
- name: samplefe-image
  newName: acrwisampledev.azurecr.io/wi-sample/samplefe-dev
  newTag: azd-deploy-1756283777
